# Banking Transaction Analytics
1. KPI Analysis

Total Revenue

Avg Transaction

Active Customers

Success Rate

2. Time Analysis

Monthly revenue

Quarterly trend

Weekend vs Weekday

Peak transaction hours

3. Customer Analysis

Age distribution

Occupation spending

Gender analysis

Income vs spending

4. Banking Analysis

Payment methods

Channel usage

Merchant categories

Branch performance

5. Plotly Interactive Charts

# Banking Transaction Analytics

## Notebook 2 — Exploratory Data Analysis

**Objective**

- Generate business KPIs
- Analyze customer behaviour
- Analyze revenue trends
- Visualize banking performance

In [3]:
import micropip
await micropip.install("plotly")

In [4]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [5]:
master = pd.read_csv("banking_master.csv")

master["transaction_datetime"] = pd.to_datetime(master["transaction_datetime"])

master.head()

,transaction_id,account_id,merchant_id,branch_id,transaction_datetime,transaction_type,amount,payment_method,channel,opening_balance,closing_balance,transaction_status,reference_no,customer_id,account_type,balance,credit_limit,account_status,opened_date,name,gender,age,occupation,annual_income,customer_city,join_date,merchant_name,category,mcc_code,merchant_city,branch_name,city,region,year,month,month_no,quarter,day,weekday,hour,is_weekend,transaction_band
0,TXN0000001,ACC002975,MER104,BR025,2025-12-18 22:48:00,Debit,4086.42,UPI,Mobile Banking,85557.75,81471.33,Success,REF9729789661,CUST02975,Savings,85557.75,0,Active,2024-02-22,Rohit Mehta,Female,54,Designer,445724,Bengaluru,2025-02-28,Shopping Store 104,Shopping,5976,Ahmedabad,Vellore Branch,Vellore,South,2025,December,12,Q4,18,Thursday,22,False,Medium
1,TXN0000002,ACC004775,MER002,BR023,2025-05-18 10:37:00,Credit,1793.55,UPI,Internet Banking,105884.92,107678.47,Success,REF9434640177,CUST04775,Savings,105884.92,0,Active,2024-09-05,Rohit Iyer,Female,51,Analyst,865371,Kochi,2024-04-13,Flipkart,Shopping,5311,Surat,Indore Branch,Indore,Central,2025,May,5,Q2,18,Sunday,10,True,Medium
2,TXN0000003,ACC005627,MER009,BR019,2026-04-13 02:32:00,Debit,9547.04,NEFT,Internet Banking,336343.50,326796.46,Success,REF2889483864,CUST00539,Savings,336343.50,0,Active,2023-08-12,Aman Gupta,Female,34,Doctor,2423909,Kochi,2025-04-17,Uber,Travel,4121,Ranchi,Ranchi Branch,Ranchi,East,2026,April,4,Q2,13,Monday,2,False,High
3,TXN0000004,ACC002167,MER006,BR005,2025-06-12 18:22:00,Debit,764.22,UPI,ATM,96423.36,95659.14,Success,REF4676695532,CUST02167,Current,96423.36,0,Active,2023-08-25,Ananya Reddy,Female,28,Engineer,1595354,Noida,2023-12-11,Swiggy,Food,5812,Raipur,Coimbatore Branch,Coimbatore,South,2025,June,6,Q2,12,Thursday,18,False,Low
4,TXN0000005,ACC005845,MER085,BR010,2026-05-01 16:42:00,Debit,2599.33,Debit Card,Mobile Banking,46877.06,44277.73,Success,REF1725477974,CUST02405,Current,46877.06,0,Active,2023-01-22,Neha Sharma,Female,41,Teacher,831421,Kolkata,2020-08-18,Healthcare Store 85,Healthcare,5764,Bhopal,Jaipur Branch,Jaipur,West,2026,May,5,Q2,1,Friday,16,False,Medium

In [6]:
#Executive Kpi Calculation that appears on the top of the dashboard

total_revenue = master["amount"].sum()

total_transactions = master["transaction_id"].count()

unique_customers = master["customer_id"].nunique()

avg_transaction = master["amount"].mean()

success_rate = (
    master["transaction_status"]
    .eq("Success")
    .mean()*100
)

In [7]:
# Converting Kpi to dataframe for better reading
kpi = pd.DataFrame({
    "KPI":[
        "Total Revenue",
        "Transactions",
        "Customers",
        "Average Transaction",
        "Success Rate"
    ],
    "Value":[
        f"₹ {total_revenue:,.2f}",
        f"{total_transactions:,}",
        f"{unique_customers:,}",
        f"₹ {avg_transaction:,.2f}",
        f"{success_rate:.2f}%"
    ]
})

kpi

                   KPI             Value
0        Total Revenue  ₹ 398,000,228.92
1         Transactions           100,000
2            Customers             5,000
3  Average Transaction        ₹ 3,980.00
4         Success Rate            95.98%

In [8]:
#Monthly Revenue Trend
monthly = (
    master
    .groupby(["year","month_no","month"], as_index=False)
    ["amount"]
    .sum()
    .sort_values(["year","month_no"])
)

monthly

    year  month_no      month       amount
0   2025         1    January  20675483.04
1   2025         2   February  19289737.26
2   2025         3      March  19926348.59
3   2025         4      April  19178651.72
4   2025         5        May  19139879.34
5   2025         6       June  19145186.12
6   2025         7       July  21223956.06
7   2025         8     August  20985332.80
8   2025         9  September  19945519.86
9   2025        10    October  19876881.08
10  2025        11   November  20032342.91
11  2025        12   December  21458138.21
12  2026         1    January  20434353.26
13  2026         2   February  19206373.71
14  2026         3      March  21254003.02
15  2026         4      April  19465260.12
16  2026         5        May  20531148.42
17  2026         6       June  18460659.04
18  2026         7       July  20146257.85
19  2026         8     August  17624716.51

In [13]:
fig = px.line(
    monthly,
    x="month",
    y="amount",
    color="year",
    markers=True,
    title="Monthly Revenue Trend"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Revenue"
)

from IPython.display import display, HTML

display(
    HTML(
        fig.to_html(
            include_plotlyjs="cdn",
            full_html=False,
            default_width="900px",
            default_height="500px"
        )
    )
)

In [14]:
# Revenue by region
region = (
    master
    .groupby("region", as_index=False)
    ["amount"]
    .sum()
    .sort_values("amount", ascending=False)
)

region

    region       amount
3    South  95625226.47
4     West  79545763.76
2    North  78987261.86
1     East  78532879.01
0  Central  65309097.82

In [21]:
from IPython.display import HTML, display

def show_plot(fig, width=900, height=500):
    display(
        HTML(
            fig.to_html(
                include_plotlyjs="cdn",
                full_html=False,
                default_width=f"{width}px",
                default_height=f"{height}px"
            )
        )
    )

fig = px.pie(
    region,
    names="region",
    values="amount",
    hole=0.45,
    title="Regional Revenue Distribution"
)

show_plot(fig)

In [22]:
#Merchant By Category
category = (
    master
    .groupby("category", as_index=False)
    ["amount"]
    .sum()
    .sort_values("amount", ascending=False)
)

category

        category        amount
5       Shopping  2.213641e+08
6         Travel  4.994628e+07
2           Fuel  3.254782e+07
3        Grocery  2.620771e+07
7      Utilities  2.499034e+07
1           Food  2.009240e+07
4     Healthcare  1.282677e+07
0  Entertainment  1.002477e+07

In [23]:
fig = px.bar(
    category,
    x="amount",
    y="category",
    orientation="h",
    text_auto=".2s",
    title="Revenue by Merchant Category",
    color="amount",
    color_continuous_scale="Blues"
)

fig.update_layout(
    xaxis_title="Revenue (₹)",
    yaxis_title="Merchant Category",
    template="plotly_white"
)

show_plot(fig)

In [24]:
#Branch Performance Analysis

branch = (
    master
    .groupby("branch_name", as_index=False)["amount"]
    .sum()
    .sort_values("amount", ascending=False)
    .head(10)
)

branch

           branch_name       amount
1     Bengaluru Branch  18772983.20
18        Noida Branch  17181004.57
12       Jaipur Branch  16998531.10
22       Ranchi Branch  16906955.60
6    Coimbatore Branch  16820385.15
17       Nagpur Branch  16772900.13
3   Bhubaneswar Branch  16576392.11
21       Raipur Branch  16455591.54
11       Indore Branch  16354399.27
0     Ahmedabad Branch  16193678.27

In [25]:
fig = px.bar(
    branch,
    x="amount",
    y="branch_name",
    orientation="h",
    text_auto=".2s",
    title="Top 10 Revenue Generating Branches",
    color="amount",
    color_continuous_scale="Blues"
)

fig.update_layout(
    xaxis_title="Revenue (₹)",
    yaxis_title="Branch"
)

show_plot(fig)

In [26]:
# Payment Method Analysis
payment = (
    master
    .groupby("payment_method", as_index=False)
    .agg(
        Transactions=("transaction_id", "count"),
        Revenue=("amount", "sum")
    )
    .sort_values("Transactions", ascending=False)
)

payment

  payment_method  Transactions       Revenue
4            UPI         39273  9.974647e+07
1     Debit Card         24683  6.483069e+07
0    Credit Card         14651  3.707903e+07
3           NEFT         11525  1.712305e+08
2           IMPS          9868  2.511357e+07

In [27]:
fig = px.bar(
    payment,
    x="payment_method",
    y="Transactions",
    text_auto=True,
    title="Transaction Volume by Payment Method",
    color="Transactions",
    color_continuous_scale="Greens"
)

show_plot(fig)

In [28]:
#Banking Channel Analysis
channel = (
    master
    .groupby("channel", as_index=False)["amount"]
    .sum()
    .sort_values("amount", ascending=False)
)

channel

            channel        amount
1  Internet Banking  1.952757e+08
2    Mobile Banking  1.125214e+08
3               POS  6.391988e+07
0               ATM  2.628328e+07

In [29]:
fig = px.pie(
    channel,
    names="channel",
    values="amount",
    hole=0.45,
    title="Revenue Distribution by Banking Channel"
)

show_plot(fig)

In [30]:
#Customer Age Distribution
fig = px.histogram(
    master,
    x="age",
    nbins=20,
    title="Customer Age Distribution",
    color_discrete_sequence=["#2563EB"]
)

fig.update_layout(
    xaxis_title="Age",
    yaxis_title="Number of Customers"
)

show_plot(fig)

In [31]:
# Occupation wise spending
occupation = (
    master
    .groupby("occupation", as_index=False)["amount"]
    .sum()
    .sort_values("amount", ascending=False)
)

occupation

        occupation       amount
5         Engineer  94592004.10
0          Analyst  47962145.24
7          Manager  46759739.58
1   Business Owner  39901682.56
4           Doctor  35396204.02
9          Student  29035616.94
6       Government  26828001.18
10         Teacher  24309731.42
2       Consultant  20807997.30
3         Designer  16227533.27
8          Retired  16179573.31

In [32]:
fig = px.bar(
    occupation,
    x="occupation",
    y="amount",
    text_auto=".2s",
    title="Revenue by Customer Occupation",
    color="amount",
    color_continuous_scale="Purples"
)

fig.update_layout(xaxis_title="Occupation")

show_plot(fig)

In [33]:
#Gender Spending Comparison
gender = (
    master
    .groupby("gender", as_index=False)
    .agg(
        Revenue=("amount", "sum"),
        Customers=("customer_id", "nunique")
    )
)

gender

   gender       Revenue  Customers
0  Female  1.955740e+08       2479
1    Male  2.024263e+08       2521

In [34]:
fig = px.bar(
    gender,
    x="gender",
    y="Revenue",
    text_auto=".2s",
    color="gender",
    title="Revenue by Gender"
)

show_plot(fig)

## Correlation Analysis

Analyze the relationship between balance, income, age and transaction amount.

In [35]:
numeric = master[
    ["amount",
     "opening_balance",
     "closing_balance",
     "balance",
     "annual_income",
     "age"]
]

corr = numeric.corr(numeric_only=True).round(2)

corr

,amount,opening_balance,closing_balance,balance,annual_income,age
amount,1.00,0.01,0.16,0.00,0.08,0.00
opening_balance,0.01,1.00,0.98,0.87,0.06,0.00
closing_balance,0.16,0.98,1.00,0.85,0.08,0.00
balance,0.00,0.87,0.85,1.00,-0.04,-0.00
annual_income,0.08,0.06,0.08,-0.04,1.00,0.11
age,0.00,0.00,0.00,-0.00,0.11,1.00

In [36]:
fig = px.imshow(
    corr,
    text_auto=True,
    color_continuous_scale="RdBu",
    title="Correlation Heatmap"
)

show_plot(fig)

In [37]:
# Peak Transaction Hours
hourly = (
    master
    .groupby("hour", as_index=False)
    .agg(
        Transactions=("transaction_id", "count"),
        Revenue=("amount", "sum")
    )
)

hourly

    hour  Transactions      Revenue
0      0          4255  16494621.71
1      1          4172  17533179.16
2      2          3989  16329197.76
3      3          4204  15790289.50
4      4          4240  16005896.61
5      5          4176  16648140.56
6      6          4191  16560950.29
7      7          4214  15464184.05
8      8          4239  17910490.73
9      9          4168  15136087.82
10    10          4240  17008496.87
11    11          4318  18686849.20
12    12          4260  16881084.66
13    13          4143  15508366.53
14    14          4198  18146029.88
15    15          4054  16441230.40
16    16          4098  16072524.33
17    17          4145  16799934.46
18    18          4071  16439840.98
19    19          4125  16171002.45
20    20          4084  15370514.73
21    21          4160  16934939.87
22    22          4163  16259701.11
23    23          4093  17406675.26

In [38]:
fig = px.line(
    hourly,
    x="hour",
    y="Transactions",
    markers=True,
    title="Peak Transaction Hours"
)

fig.update_layout(
    xaxis=dict(dtick=1),
    xaxis_title="Hour of Day",
    yaxis_title="Number of Transactions"
)

show_plot(fig)

In [39]:
#Weekend Vs Weekday
weekend = (
    master
    .groupby("is_weekend", as_index=False)
    .agg(
        Revenue=("amount", "sum"),
        Transactions=("transaction_id", "count")
    )
)

weekend["Day Type"] = weekend["is_weekend"].map({
    True:"Weekend",
    False:"Weekday"
})

weekend

   is_weekend       Revenue  Transactions Day Type
0       False  2.839305e+08         71255  Weekday
1        True  1.140697e+08         28745  Weekend

In [40]:
fig = px.bar(
    weekend,
    x="Day Type",
    y="Revenue",
    text_auto=".2s",
    color="Day Type",
    title="Weekend vs Weekday Revenue"
)

show_plot(fig)

In [44]:
#Income vs Spending
customer_spending = (
    master
    .groupby(
        ["customer_id","annual_income","gender"],
        as_index=False
    )
    .agg(
        Total_Spent=("amount","sum")
    )
)

customer_spending.head()

  customer_id  annual_income  gender  Total_Spent
0   CUST00001        2030985  Female    368627.63
1   CUST00002         115457  Female     19381.83
2   CUST00003         999318  Female     52125.35
3   CUST00004        1184151    Male     44305.90
4   CUST00005        2924684  Female     28836.22

In [47]:
fig = px.scatter(
    customer_spending,
    x="annual_income",
    y="Total_Spent",
    color="gender",
    opacity=0.6,
    title="Annual Income vs Customer Spending"
)
import numpy as np

x = customer_spending["annual_income"]
y = customer_spending["Total_Spent"]

m, b = np.polyfit(x, y, 1)

fig.add_scatter(
    x=x,
    y=m*x + b,
    mode="lines",
    name="Regression Line",
    line=dict(color="red", width=3)
)

show_plot(fig)

In [48]:
#Successful Vs Failed Transactions
status = (
    master
    .groupby("transaction_status", as_index=False)
    .agg(
        Count=("transaction_id","count")
    )
)

status["Percentage"] = (
    status["Count"]/status["Count"].sum()*100
).round(2)

status

  transaction_status  Count  Percentage
0             Failed   4017        4.02
1            Success  95983       95.98

In [49]:
fig = px.pie(
    status,
    names="transaction_status",
    values="Count",
    hole=0.55,
    title="Transaction Success Rate"
)

show_plot(fig)

In [50]:
# Revenue by Quarter
quarter = (
    master
    .groupby("quarter", as_index=False)
    ["amount"]
    .sum()
)

quarter

  quarter        amount
0      Q1  1.207863e+08
1      Q2  1.159208e+08
2      Q3  9.992578e+07
3      Q4  6.136736e+07

In [51]:
fig = px.bar(
    quarter,
    x="quarter",
    y="amount",
    text_auto=".2s",
    color="amount",
    color_continuous_scale="Teal",
    title="Quarter-wise Revenue"
)

show_plot(fig)

## Executive Business Summary

In [52]:
top_region = (
    region.sort_values("amount", ascending=False)
    .iloc[0]
)

top_branch = (
    branch.sort_values("amount", ascending=False)
    .iloc[0]
)

top_category = (
    category.sort_values("amount", ascending=False)
    .iloc[0]
)

print("="*60)
print("EXECUTIVE BUSINESS SUMMARY")
print("="*60)

print(f"""
Total Revenue        : ₹{total_revenue:,.2f}

Transactions         : {total_transactions:,}

Customers            : {unique_customers:,}

Average Transaction  : ₹{avg_transaction:,.2f}

Success Rate         : {success_rate:.2f}%

Top Region           : {top_region.region}

Top Branch           : {top_branch.branch_name}

Top Merchant Category: {top_category.category}
""")

============================================================
EXECUTIVE BUSINESS SUMMARY
============================================================

Total Revenue        : ₹398,000,228.92

Transactions         : 100,000

Customers            : 5,000

Average Transaction  : ₹3,980.00

Success Rate         : 95.98%

Top Region           : South

Top Branch           : Bengaluru Branch

Top Merchant Category: Shopping